name: ci

on:
  pull_request:
    branches: [ master ]

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix: { env: ["development", "production", "staging"] }
    environment: ${{ matrix.env }}
    defaults:
      run:
        working-directory: "./workspaces/${{ matrix.env }}"

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0
      
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Verify that the configuration files are syntactically valid
        run: terraform validate -no-color


